services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ep-super-dust-a9dgzgyx-pooler.gwc.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      KC_DB_USERNAME: neondb_owner
      KC_DB_PASSWORD: npg_3juWleMZFJ4w

      KC_HTTP_ENABLED: "true"
    command:
      - start-dev