spring.application.name=4Fit

spring.datasource.url=jdbc:postgresql://ep-super-dust-a9dgzgyx-pooler.gwc.azure.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner

spring.datasource.password=npg_3juWleMZFJ4w
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

dotenv.system-properties=true

server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/4FitRealm

keycloak.client-id=webApp-backend

keycloak.client-secret=OS7MbLvM6eSmx0sy0AcAgRQQAbb1n2iN